# This playbook will setup kubeadm on Linux hosts for Kubernetes installationls
# 1. 
# 2. 
# 3. 

- hosts: kube-cluster

  tasks:
      - name: Install ebtables, ethtool, apt-transport-https packages
        apt: 
          name: [ebtables, ethtool, apt-transport-https ]
          state: present
          update_cache: yes
      
      - name: Install Docker from Ubuntu Repos
        shell: apt-get install -y docker.io
      
      - name: Update apt-key
        shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

      - name: Update apt Repos for K8s
        shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list.d/kubernetes.list
 
      - name: Install kubeadm packages
        apt: 
          name: [kubelet, kubeadm, kubectl]
          state: present
          update_cache: yes
      - name: Disable SWAP
        shell: swapoff -a 

- hosts: kube-master
  
  tasks: 
      - name: Kubeadm Init Master with Calico CIDR
        shell: kubeadm init --pod-network-cidr=192.168.0.0/16 | tail -n2
        register: kubeadmoutput
      
      - name: Show variable contents
        debug:
            msg: "kubeadm_join_output stdout contents: {{ kubeadmoutput.stdout }}"
      
      - name:  kubectl setup directory
        shell: mkdir -p $HOME/.kube
      
      - name: kubectl setup copy conf file
        shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      
      - name: kubectl setup change permissions on conf file
        shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config
      
      - name: kubectl setup Calico
        shell: kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

      - name: Copy k8s-admin.conf to local machine
        fetch: 
          src: /etc/kubernetes/admin.conf
          dest: ~/k8s-admin.conf
          flat: yes

- hosts: kube-node
  
  tasks: 
      
      - name: Show kube-master variable contents
        debug:
          msg: "Kubeadm join command is {{ hostvars[groups['kube-master'][0]]['kubeadmoutput']['stdout'] }}"
      
      - name: Run kubeadm join from nodes
        shell: "{{ hostvars[groups['kube-master'][0]]['kubeadmoutput']['stdout'] }}"

- hosts: kube-client
  
  tasks:

      - name: Test access to the cluster using kubectl
        shell: kubectl --kubeconfig ~/k8s-admin.conf get nodes
        register: clusternodes
      
      - name: Show getnodes ouput from local group
        debug:
          msg: "Cluster nodes are online: {{ clusternodes.stdout_lines }}"

      - name: Provide instructions for accessing the cluster
        debug:
          msg: "To use this cluster specify the '--kubeconfig ~/k8s-admin.conf' with kubectl"
          msg: "kubectl --kubeconfig ~/k8s-admin.conf get nodes"