# This playbook will setup kubeadm on Linux hosts for Kubernetes installationls
# 1. 
# 2. 
# 3. 


- hosts: kube-master
  
  tasks: 
      - name: Kubeadm Init Master with Calico CIDR
        shell: hostname
        register: hostname
      
      - name: Show local Groups Variable contents with debug 
        debug:
          msg: "Current hostname is: {{ hostname.stdout }}"

      - name: Make local Groups variables persistent to other host groups
        set_fact:
          hostname: "{{ hostname }}"

      - name: Copy k8s-admin.conf to local machine
        fetch: 
          src: /etc/kubernetes/admin.conf
          dest: ~/admin.conf
          flat: yes


- hosts: kube-node
  
  tasks: 
      
      - name: Show another Host Groups Variable contents (fact) with debug 
        debug:
          msg: "kube-master variable hostname is {{ hostvars[groups['kube-master'][0]]['hostname']['stdout'] }}"

- hosts: kube-client
  
  tasks:

      - name: Test access to the cluster using kubectl
        shell: kubectl --kubeconfig ~/admin.conf get nodes
        register: clusternodes
      
      - name: Show getnodes ouput from local group
        debug:
          msg: "{{ clusternodes.stdout_lines }}"

      - name: Provide instructions for accessing the cluster
        debug:
          msg: "To use this cluster specify the '--kubeconfig ~/k8s-admin.conf' with kubectl"
          msg: "kubectl --kubeconfig ~/k8s-admin.conf get nodes"

